export const TOKEN_MANAGEMENT_PREFIX = "TOKEN_MANAGEMENT_PREFIX";
export const DATA_ACCOUNT_PREFIX = "DATA_ACCOUNT_PREFIX";
export const SETTING_ACCOUNT_PREFIX = "SETTING_ACCOUNT_PREFIX";
export const EZHUB_PREFIX = "EZHUB_PREFIX";
export const ADD_EZHUB_PREFIX = "ADD_EZHUB_PREFIX";
export const DELETE_EZHUB_PREFIX = "DELETE_EZHUB_PREFIX";
export const DEFAULT_EZHUB_STATE = "DEFAULT_EZHUB_STATE";
export const RENAME_EZHUB_STATE = "RENAME_EZHUB_STATE";
export const FEE_SCHEDULE_RP_PREFIX = "FEE_SCHEDULE_RP_PREFIX";
export const CS_LOOKUP_SLICE = "CS_LOOKUP_SLICE";
export const PERMISSION_SLICE = "PERMISSION_SLICE";
export const PS_REPORT_SLICE = "PS_REPORT_SLICE";
export const CS_REPORT_SLICE = "CS_REPORT_SLICE";
export const MARGIN_T_SLICE = "MARGIN_T_SLICE";
export const STOCK_CODE_HNX_SLICE = "STOCK_CODE_HNX_SLICE";
export const COMMENTS_SLICE = "COMMENTS_SLICE";
export const CHART_STATIC_SLICE = "CHART_STATIC_SLICE";
export const PS_CHART_STATIC_SLICE = "PS_CHART_STATIC_SLICE";

export const ASSET_REPORT_SLICE = "ASSET_REPORT_SLICE";
export const SAVING_REPORT_SLICE = "SAVING_REPORT_SLICE";

export const ACCOUNT_INFO_PREFIX = "ACCOUNT_INFO_PREFIX";
export const UTILITY_PREFIX = "UTILITY_PREFIX";
export const STOCK_PREFIX = "STOCK_PREFIX";
